[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
command = "node ./update-netlify-version.js && npm i && npm run build"
publish = ".next"

[context.production.environment]
  NEXT_PUBLIC_PANGEA_API_URL = "https://api.internal.dev.pangea.io"
  NEXT_PUBLIC_STRIPE_API_KEY = "pk_test_51Hy4mDAwdnArAVlS4RbZ8d4VXkwcVfAdstBeqBOsvKRjaZZoYsA95V9dZPhgUKODaQZYanxhmTA093Kykmq9nrNQ00fGcS0IpW"
  NEXT_VERSION = "^13.5.6"
  NETLIFY_VERSION = "^4.41.3"

[context.branch-deploy.environment]
  NEXT_PUBLIC_PANGEA_API_URL = "https://api.internal.dev.pangea.io"
  NEXT_PUBLIC_STRIPE_API_KEY = "pk_test_51Hy4mDAwdnArAVlS4RbZ8d4VXkwcVfAdstBeqBOsvKRjaZZoYsA95V9dZPhgUKODaQZYanxhmTA093Kykmq9nrNQ00fGcS0IpW"
  NEXT_VERSION = "^13.5.6"
  NETLIFY_VERSION = "^4.41.3"

[context.deploy-preview.environment]
  NEXT_PUBLIC_PANGEA_API_URL = "https://api.internal.dev.pangea.io"
  NEXT_PUBLIC_STRIPE_API_KEY = "pk_test_51Hy4mDAwdnArAVlS4RbZ8d4VXkwcVfAdstBeqBOsvKRjaZZoYsA95V9dZPhgUKODaQZYanxhmTA093Kykmq9nrNQ00fGcS0IpW"
  NEXT_VERSION = "13.4.19"
  NETLIFY_VERSION = "4.41.1"

[context.main.environment]
  NEXT_PUBLIC_PANGEA_API_URL = "https://api.internal.dev.pangea.io"
  NEXT_PUBLIC_STRIPE_API_KEY = "pk_test_51Hy4mDAwdnArAVlS4RbZ8d4VXkwcVfAdstBeqBOsvKRjaZZoYsA95V9dZPhgUKODaQZYanxhmTA093Kykmq9nrNQ00fGcS0IpW"
  NEXT_VERSION = "^13.5.6"
  NETLIFY_VERSION = "^4.41.3"
