timeout: 1800s # 60 x 30m
substitutions:
  _NODE_VERSION: "18"
steps:
  #    # INSTALL PROJECT DEPENDENCIES (npm ci)
  #    - id: 'frontend:npm:ci'
  #      name: 'node:${_NODE_VERSION}'
  #      dir: 'pangea-web'
  #      entrypoint: npm
  #      args: ['ci']
  #      env:
  #        - 'NEXT_TELEMETRY_DISABLED=1'
  #
  #    # INSTALL SWC DEPENDENCIES (npm install -E --save-optional @next/swc-linux-x64-gnu)
  #    - id: 'frontend:npm:install'
  #      name: 'node:${_NODE_VERSION}'
  #      dir: 'pangea-web'
  #      entrypoint: npm
  #      args: [
  #        'install',
  #        '-E',
  #        '--save-optional',
  #        '@next/swc-linux-x64-gnu'
  #      ]
  #
  #    # RUN LINTER (npm run lint)
  #    - id: 'frontend:npm:lint'
  #      name: 'node:${_NODE_VERSION}'
  #      dir: 'pangea-web'
  #      entrypoint: npm
  #      args: ['run', 'lint']
  #
  #    # UNIT TEST (JEST) (npm run test:ci)
  #    - id: 'frontend:npm:test'
  #      name: 'node:${_NODE_VERSION}'
  #      dir: 'pangea-web'
  #      entrypoint: npm
  #      args: ['run', 'test:ci']

  #    # frontend:docker:deps:pull
  #    - id: 'frontend:docker:deps:pull'
  #      name: 'gcr.io/cloud-builders/docker'
  #      args: [
  #          'pull',
  #          'gcr.io/$PROJECT_ID/pangea-frontend-deps:latest'
  #      ]

  # frontend:docker:pull
  - id: "frontend:docker:pull"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "pull",
        "gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$_DEPLOYMENT_PREFIX",
      ]

  # frontend:docker:build
  - id: "frontend:docker:build"
    name: "gcr.io/cloud-builders/docker"
    env:
      - CFE_NPM_TOKEN=$_CFE_NPM_TOKEN
    args:
      [
        "build",
        "--cache-from=gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$_DEPLOYMENT_PREFIX",
        "--build-arg",
        "NEXT_PUBLIC_PANGEA_API_URL=$_NEXT_PUBLIC_PANGEA_API_URL",
        "--build-arg",
        "NEXT_PUBLIC_STRIPE_API_KEY=$_NEXT_PUBLIC_STRIPE_API_KEY",
        "--build-arg",
        "NEXT_PUBLIC_MUI_LICENSE=$_NEXT_PUBLIC_MUI_LICENSE",
        "--build-arg",
        "CFE_NPM_TOKEN=$_CFE_NPM_TOKEN",
        "--build-arg",
        "NEXT_PUBLIC_ENABLE_FEATURE_FLAG_DEVTOOL=$_NEXT_PUBLIC_ENABLE_FEATURE_FLAG_DEVTOOL",
        "--tag=gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$SHORT_SHA",
        "--file=dockerfiles/Dockerfile__Frontend",
        ".",
      ]

  # frontend:docker:push:temp
  - id: "frontend:docker:push"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$SHORT_SHA",
      ]

  # frontend:gcloud:run
  - id: "frontend:gcloud:run"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_DEPLOYMENT_PREFIX-pangea-frontend",
        "--port=3000",
        "--verbosity=debug",
        "--image=gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$SHORT_SHA",
        "--region=$_REGION",
        "--platform=managed",
        "--allow-unauthenticated",
        "--min-instances=1",
        "--set-env-vars=NEXT_PUBLIC_PANGEA_API_URL=$_NEXT_PUBLIC_PANGEA_API_URL",
        "--set-env-vars=CFE_NPM_TOKEN=$_CFE_NPM_TOKEN",
        "--set-env-vars=NEXT_PUBLIC_STRIPE_API_KEY=$_NEXT_PUBLIC_STRIPE_API_KEY",
        "--set-env-vars=NEXT_PUBLIC_TRACE_API=$_NEXT_PUBLIC_TRACE_API",
        "--set-env-vars=NEXT_PUBLIC_MUI_LICENSE=$_NEXT_PUBLIC_MUI_LICENSE",
        "--set-env-vars=NEXT_PUBLIC_ENABLE_FEATURE_FLAG_DEVTOOL=$_NEXT_PUBLIC_ENABLE_FEATURE_FLAG_DEVTOOL",
      ]

  # frontend:docker:tag:updated
  - id: "frontend:docker:tag:updated"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$SHORT_SHA",
        "gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$_DEPLOYMENT_PREFIX",
      ]

  # frontend:docker:push:updated
  - id: "frontend:docker:push:updated"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$_DEPLOYMENT_PREFIX",
      ]

images:
  - "gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/$_DEPLOYMENT_PREFIX-pangea-frontend:$_DEPLOYMENT_PREFIX"
